name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
